<!DOCTYPE html>
<html>

<head>
    <title>Document Inventory - {{ $user->name }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #333;
            margin: 40px;
        }

        .header {
            border-bottom: 2px solid #000;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .company-name {
            font-size: 24px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 2px;
        }

        .report-title {
            font-size: 18px;
            color: #666;
            margin-top: 5px;
        }

        .employee-info {
            margin-bottom: 40px;
        }

        .employee-info p {
            margin: 5px 0;
            font-size: 12px;
        }

        .employee-info strong {
            width: 100px;
            display: inline-block;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background: #f5f5f5;
            text-align: left;
            padding: 12px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
            border-bottom: 2px solid #eee;
        }

        td {
            padding: 12px;
            font-size: 11px;
            border-bottom: 1px solid #eee;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 9px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }

        .status {
            padding: 4px 8px;
            border-radius: 4px;
            font-weight: bold;
            font-size: 9px;
        }

        .type-tag {
            font-weight: bold;
            color: #2563eb;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="company-name">HRIS PREMIUM</div>
        <div class="report-title">Document Inventory Report</div>
    </div>

    <div class="employee-info">
        <p><strong>Employee:</strong> {{ $user->name }}</p>
        <p><strong>Department:</strong> {{ $user->employee_profile->department ?? 'N/A' }}</p>
        <p><strong>Date Generated:</strong> {{ $date }}</p>
        <p><strong>Total Files:</strong> {{ count($documents) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Document Title</th>
                <th>Expiry Date</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($documents as $doc)
                <tr>
                    <td class="type-tag">{{ $doc->type }}</td>
                    <td>{{ $doc->title }}</td>
                    <td>{{ $doc->expiry_date ?? 'No Expiry' }}</td>
                    <td style="color: #666; font-style: italic;">{{ $doc->notes ?: '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by HRIS Premium Management System &bull; {{ $date }} &bull; Confidential
    </div>
</body>

</html>
